codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        flags:
          - unit
        # advanced
        branches: master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  branches: *
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: no        # [yes :: must have a head report to post]
