package:
  name: piq
  version: "0.5.0"

source:
  git_rev: "v0.5.0"
  git_url: https://github.com/photosynthesis-team/piq.git
  git_depth: 1

requirements:
  run:
    - pytorch>=1.2.0,!=1.5.0
    - torchvision>=0.4.0,!=0.6.0
    - scipy==1.3.3
    - gudhi>=3.2

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  home: https://github.com/photosynthesis-team/piq
  license: Apache License 2.0
  license_file: LICENSE