package:
  name: piq
  version: "0.5.0"

source:
  git_rev: "v0.5.0"
  git_url: https://github.com/photosynthesis-team/piq.git
  git_depth: 1

requirements:
  build:
    - python>=3
    - setuptools
    - torch>=1.2.0,!=1.5.0
    - scipy==1.3.3
    - torchvision>=0.4.0,!=0.6.0
    - gudhi>=3.2

build:
  script: python setup.py install

about:
  home: https://github.com/photosynthesis-team/piq
  license: Apache 2.0