{% set data = load_setup_py_data() %}
package:
  name: piq
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/photosynthesis-team/piq.git
  git_depth: 1

requirements:
  build:
    - python
    - pytorch>=1.2.0
    - torchvision>=0.4.0
    - scipy==1.3.3
    - gudhi>=3.2
  run:
    - python
    - pytorch>=1.2.0
    - torchvision>=0.4.0
    - scipy==1.3.3
    - gudhi>=3.2

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  home: https://github.com/photosynthesis-team/piq
  license: Apache License 2.0
  license_file: LICENSE
  summary: PyTorch Image Quality. Collection of measures and metrics for automatic image quality assessment in various image-to-image tasks such as denoising, super-resolution, image generation etc.
