name: deployment to conda

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Miniconda
        run: |
          sudo apt-get update
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          hash -r
          conda update -q conda
      - name: Install dependencies
        run: |
          conda install -y anaconda-client conda-build conda-verify
          conda config --set anaconda_upload yes
      - name: Build and publish
        env:
          CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
          CONDA_USERNAME: ${{ secrets.CONDA_USERNAME }}
        run: |
          conda build --token $CONDA_TOKEN --user $CONDA_USERNAME --quiet --no-test --output-folder conda_build ./conda/
          conda convert --platform win-64 conda_build/linux-64/*.tar.bz2 -o conda_build/
          conda convert --platform osx-64 conda_build/linux-64/*.tar.bz2 -o conda_build/